ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views

app_name = "cart"

urlpatterns = [
    path('addtocart/<n>', views.addtocart, name="addtocart"),
    path('cartview', views.cartview, name="cartview"),
    path('cart_remove/<n>', views.cart_remove, name="cart_remove"),
    path('full_remove/<n>', views.full_remove, name="full_remove"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),


]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('search', include('search.urls')),
    path('cart', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path

from search import views

app_name = "search"

urlpatterns = [
    path('search', views.search, name="search"),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
    path('', views.allcategories, name="allcat"),
    path('allprod/<p>', views.allproducts, name="allprod"),
    path('details/<c>', views.details, name="details"),
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
]

ecommerce/cart/models.py
from django.contrib.auth.models import User
from django.db import models

from shop.models import Product
from django.http import HttpResponse


# Create your models here.

class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity * self.product.price


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items = models.IntegerField()
    address = models.TextField()
    phone = models.IntegerField()
    order_status = models.CharField(max_length=20,default="pending")
    delivery_status = models.CharField(max_length=20,default="pending")
    ordered_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Account(models.Model):
    acctnum = models.CharField(max_length=20)
    accttype = models.CharField(max_length=20)
    amount = models.IntegerField()

    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from cart.models import Cart
from shop.models import Product

from cart.models import Account

from cart.models import Order


# Create your views here.

@login_required
def cartview(request):
    total = 0
    u = request.user
    try:
        cart = Cart.objects.filter(user=u)
        for i in cart:
            total += i.quantity * i.product.price
    except:
        pass
    return render(request, 'cartview.html', {'c': cart, 'total': total})


@login_required
def addtocart(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (p.stock>0):
            cart.quantity += 1
            cart.save()
            p.stock -= 1
            p.save()
    except:
        if (p.stock > 0):
            cart = Cart.objects.create(product=p, user=u, quantity=1)
            cart.save()
            p.stock -= 1
            p.save()

    return cartview(request)


@login_required
def cart_remove(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (cart.quantity > 1):
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            p.save()
        else:
            cart.delete()
            p.stock += 1
            p.save()

    except:
        pass

    return cartview(request)


@login_required
def full_remove(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock += cart.quantity
        p.save()

    except:
        pass

    return cartview(request)


@login_required
def orderform(request):
    if request.method == "POST":
        a = request.POST['a']
        p = request.POST['p']
        n = request.POST['n']

        u = request.user
        cart = Cart.objects.filter(user=u)

        total = 0
        for i in cart:
            total += i.quantity * i.product.price

        try:
            ac = Account.objects.get(acctnum=n)  # To retrive the acctobject
            if (ac.amount >= total):
                ac.amount = ac.amount - total
                ac.save()

                for i in cart:
                    o = Order.objects.create(user=u, product=i.product, address=a, phone=p, no_of_items=i.quantity,
                                             order_status="paid")
                    o.save()
                cart.delete()
                msg = "Your order placed successfully"
                return render(request, 'orderdetail.html', {'msg': msg})
            else:
                msg = "Insufficient amount.You can't place order"
                return render(request, 'orderdetail.html', {'msg': msg})

        except:
            pass

    return render(request, 'orderform.html')


@login_required
def orderview(request):
    u = request.user
    o = Order.objects.filter(user=u)
    return render(request, 'orderview.html', {'o': o, 'u': u.username})

ecommerce/search/views.py
from django.db.models import Q
from django.shortcuts import render

from shop.models import Product


# Create your views here.

def search(request):
    query = ""
    products = None
    if (request.method == "POST"):
        query = request.POST['q']
        if query:
            products = Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))
    return render(request, 'search.html', {'query': query, 'p': products})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />



</head>
<body>

<header>
    <center>
        <img src="{% static 'images/logo.jpg' %}" class="rounded-circle" height="200px" width="200px">
    </center>


<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="#">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-light" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allprod' i.name %}">{{i.name}}</a></li>
            {% endfor %}

          </ul>
      </li>

        {% if user.is_authenticated %}


            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'shop:logout' %}">Logout</a>
            </li>
         {% if user.is_superuser == False %}

            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping fs-4"></i><sup class="mb-2 fs-6">{{count}}</sup> </a>
            </li>

           <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'cart:orderview' %}">My Order </a>
            </li>
          {% endif %}
          {% else %}

            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'shop:register' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'shop:login' %}">Login</a>
            </li>
          {% endif %}


      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

</header>

{% block content %}
{% endblock %}


<footer>
  <div class="footer p-2 text-light">
    <p>
            <i class="fa-solid fa-copyright"></i>
            Myshop Pvt Ltd.All Rights Reserved
    </p>
  </div>
</footer>

</body>
</html>

ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row fs-5 text-center">
        <h3 class="text-center">Shopping Cart</h3>
        <div class="col-sm-8">
            <table class="table table-bordered">
            <tr>
                <th colspan="5">
                    Cart Items
                </th>
            </tr>


            {% for i in c %}
            <tr>
                <td>
                    <img src="{{i.product.image.url}}" height="150px" width="150px">
                </td>
                <td><h6>{{i.product.name}}</h6></td>
                <td>
                    <h6>Product Id:{{i.product.id}}</h6>
                    <h6>Unit Price:{{i.product.price}}</h6>
                    <h6>Quantity:{{i.quantity}}*{{i.product.price}}</h6>
                </td>
                <td>
                    Subotal:{{i.subtotal}}
                </td>

                <td>
                    {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-square-plus fs-5"></i></a>
                        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-minus fs-5"></i></a>
                        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash fs-5"></i></a>

                    {% else %}
                        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-minus fs-5"></i></a>
                        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash fs-5"></i></a>

                    {% endif %}

                </td>

            </tr>

            {% endfor %}

        </table>

        </div>

        <div class="col-sm-4" style="position:relative;">
            <table class="table table-bordered">
            <tr>
                <th colspan="5">
                    Check Out
                </th>
            </tr>
            <tr>
               <td>
                   TOTAL: {{total}}
               </td>
            </tr>
            </table>
            <a href="{% url 'cart:orderform' %}" class="btn btn-danger" style="position:absolute; left:10px;">PlaceOrder</a>
            <a href="{% url 'shop:allcat' %}" class="btn btn-danger" style="position:absolute; right:10px;">Continue Shopping</a>
        </div>
    </div>
</div>


{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/banner.jpg' %}"  height="600px" width="1520px">
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">Our Collections</h3>
    <p style="text-align:justify; line-height:2;">
        E commerce is the process of buying and selling goods and services online. It has become increasingly popular in recent years, as it offers a convenient and efficient way to shop. There are many advantages to using e commerce, including the ability to compare prices, access a wider range of products, and enjoy greater convenience. It is also typically faster and more convenient than traditional shopping methods.

    </p>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">

        {% for i in c %}

        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
              <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top">
              <div class="card-body">
                <h5 class="card-title text-center">{{i.name}}</h5>
                <a href="{% url 'shop:allprod' i.name %}" class="btn btn-primary" style="position:relative; left:35%;">Products</a>
              </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-5 p-3">
            <img src="{{p.image.url}}" height="300px" width="300px">

        </div>

        <div class="col-sm-7 p-1">
            <h3>{{p.name}}<br></h3>
            <p class="lh-base" style="text-align:justify;">{{p.desc}}<br><br></p>
            <b>{{p.price}}<br></b>
            {{p.stock}}<br>


            {% if user.is_superuser == True %}
            {% if p.stock == 0 %}
            <h2>Out of stock</h2>
            <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5 ">ADD STOCK</a>
            {% else %}
            <h2>Product in stock</h2>
            <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5 ">ADD STOCK</a>
            {% endif %}


            {% else %}
            {% if p.stock == 0 %}
            <h2>Out of stock</h2>
            {% else %}
            <a href="{% url 'cart:addtocart' p.name %}" class="btn btn-danger" >Add to Cart</a>
            {% endif %}
            {% endif %}

        </div>
    </div>
</div>




{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="container" style="margin-bottom:100px;">
    <h2>Login</h2>
    <form method="POST">
        {% csrf_token %}
      <div class="mb-3">
        <label class="form-label">User name</label>
        <input type="text" class="form-control" name="u" placeholder="Enter the username">

      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" name="p" id="exampleInputPassword1" placeholder="Enter the password">
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
</center>

{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
    <br>
    <br>
    <h3>
        {{msg}}
    </h3>
    <br>
    <br>

    <h4 class="text-danger"> Thank You....</h4>
    <br>
    <br>
    <h4>
        <a href="{% url 'shop:allcat' %}">Continue Shopping</a>
    </h4>


</center>


{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>

    <div class="container">
         <h3>Order Form</h3>

        <form method="POST">
            {% csrf_token %}
          <div class="mb-3">
            <label  class="form-label">Address</label>
            <input type="text" class="form-control" name="a" placeholder="Enter the address" >
          </div>

          <div class="mb-3">
            <label  class="form-label">Phone</label>
            <input type="number" class="form-control" name="p" placeholder="Enter the phone number">
          </div>

          <div class="mb-3">
            <label  class="form-label">Account Number</label>
            <input type="number" class="form-control" name="n" placeholder="Enter the account number">
          </div>


          <button type="submit" class="btn btn-danger">Submit</button>
        </form>





    </div>
</center>


{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container" >
    <div class="row mt-5">
        <h4 class="text-center text-danger">Name of Customer:{{u}}</h4>
        {% for i in o %}
        <div class="col-sm-4 mt-3" style="margin-left:50px;">
            <img src="{{i.product.image.url}}" height="200px" width="200px">
        </div>
        <div class="col-sm-6 text-center mt-3">
            <h6>Product_name: {{i.product.name }}</h6>
            <h6>Product_price:{{i.product.price }}</h6>
            <h6>Delivery_address:{{i.address }}</h6>
            <h6>Phone:{{i.phone }}</h6>
            <h6>No_of_items:{{i.no_of_items }}</h6>
            <h6>Ordered on:{{i.ordered_date }}</h6>
            <h6 class="text-success">Delivery_status:{{i.delivery_status }}</h6>
        </div>

    </div>
      {% endfor %}
</div>



{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>
    <img src="{{c.image.url}}"  height="600px" width="1520px">
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
    <p style="text-align:justify; line-height:2;">{{c.desc}}</p>
</div>


<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
              <img src="{{i.image.url}}" class="card-img-top" height="286px" width="286px" alt="...">
              <div class="card-body">
                <h5 class="card-title">{{i.name}}<br>{{i.price}}</h5>
                <a href="{% url 'shop:details' i.name %}" class="btn btn-primary">Details</a>
              </div>
            </div>


        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <div class="container" style="margin-bottom:100px;">



   <h2>Register</h2>


<form method="POST">
    {% csrf_token %}
      <div class="mb-3">
    <label  class="form-label">Username</label>
    <input type="text" class="form-control" placeholder="Enter the username" name="u">
  </div>

      <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="p" placeholder="Enter the password" >
  </div>

      <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cp" id="exampleInputPassword1" placeholder="Enter the confirm password">
  </div>


  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="e" placeholder="Enter the emailaddress">

  </div>
       <div class="mb-3">
    <label  class="form-label">First name</label>
    <input type="text" class="form-control" name="f" placeholder="Enter the firstname" >
  </div>
      <div class="mb-3">
    <label  class="form-label">Last name</label>
    <input type="text" class="form-control" name="l" placeholder="Enter the lastname">
  </div>



  <button type="submit" class="btn btn-primary">Submit</button>
</form>
 </div>
</center>


{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <h3>You have searched for {{query}}</h3>

</center>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% if p %}
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
              <img src="{{i.image.url}}" class="card-img-top" height="286px" width="286px" alt="...">
              <div class="card-body">
                <h5 class="card-title">{{i.name}}<br>{{i.price}}</h5>
                <a href="{% url 'shop:details' i.name %}" class="btn btn-primary">Details</a>
              </div>
            </div>
        </div>

        {% endfor %}
        {% else %}
        <h4 class="text-center">No result found</h4>
        {% endif %}

    </div>
</div>

{% endblock %}